CFLAGS=-Wall -Werror -O3 -fopenmp -DUSE_LESS_MEMORY
LDFLAGS=-O3 -fopenmp

all: meshed-lessmem

clean:
	$(RM) *.o

meshed-lessmem: main.o timeval_diff.o raster.o outlet_list.o outlets.o delineate.o hierarchy.o
	$(CC) $(LDFLAGS) -o $@ $^ `gdal-config --libs`

%.o: %.c
	$(CC) $(CFLAGS) -c $<
